var five = 5;
var ten = 10;
console.log('test 1 five is equal to five?');
console.log(five == 5);
console.log("test 2 ten = 10");
console.log(ten == 10);
console.log(" test 3 :ten is not equal to five");
console.log(ten != five);
console.log("Test 4: ten is greater than five");
console.log(ten > five);
console.log("Test 5: five is smaller than ten");
console.log(five < ten);
console.log("Test 6: Ten is Smaller than 5");
console.log(ten < five);
console.log("Test 7: Five is = to ten");
console.log(five == ten);
console.log("Test 8: ten multiply by five = 7");
console.log(ten * five == 7);
console.log("Test 9: Ten + five is equals to 10");
console.log(ten + five == 10);
console.log("Test 10 : Ten ^ five is equals to 100");
console.log(Math.pow(ten, five) == 100);
console.log("Test 8: ");
